osx_image: xcode11.2
language: swift
script: 
  - xcodebuild -project Geo.xcodeproj -scheme Geo -configuration Debug -derivedDataPath $HOME/Geo build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

