name: BuildOnPush

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        xcodebuild -project Geo.xcodeproj -scheme Geo -configuration Debug -derivedDataPath $HOME/Geo build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
